export const MOCK_TRANSACTIONS = [
  {
    id: 'm001', slip_no: 'BR001-260001',
    salutation: 'Mr.', unitholder_name: 'Rajesh Kumar Sharma', pan: 'ABCDE1234F', folio_no: 'F123456',
    scheme_id: 's001', scheme_name: 'UNION Large Cap Fund', plan: 'Regular', option: 'Growth',
    facility: 'Lumpsum', frequency: 'One Time',
    transaction_types: ['PURCHASE'],
    purchase_payment_mode: 'Cheque', purchase_amount: 50000,
    purchase_amount_words: 'Fifty Thousand Only',
    purchase_cheque_utr_no: 'CHQ123456', purchase_transaction_date: '2026-06-07',
    purchase_source_bank_ac: '12345678901', purchase_source_bank_name: 'HDFC Bank',
    purchase_source_branch: 'Andheri East', purchase_account_type: 'Savings',
    purchase_third_party_declaration: false,
    submitted_at: '2026-06-07T10:23:00Z', applicable_nav_date: '2026-06-07', status: 'RECONCILED', slip_image_path: null,
    broker_code_arn: 'ARN-12345', sub_broker_arn: 'BR001', euin: 'E-123456',
    euin_declaration: false, ref_no: 'BR001-260001',
  },
  {
    id: 'm002', slip_no: 'BR001-260002',
    salutation: 'Ms.', unitholder_name: 'Priya Nair', pan: 'FGHIJ5678K', folio_no: 'F234567',
    scheme_id: 's002', scheme_name: 'UNION Flexi Cap Fund', plan: 'Direct', option: 'Growth',
    facility: 'SIP', frequency: 'Monthly',
    transaction_types: ['PURCHASE'],
    purchase_payment_mode: 'NEFT', purchase_amount: 25000,
    purchase_amount_words: 'Twenty Five Thousand Only',
    purchase_cheque_utr_no: 'UTR987654321', purchase_transaction_date: '2026-06-07',
    purchase_source_bank_ac: '98765432101', purchase_source_bank_name: 'ICICI Bank',
    purchase_source_branch: 'Bandra West', purchase_account_type: 'Savings',
    purchase_third_party_declaration: false,
    submitted_at: '2026-06-07T11:45:00Z', applicable_nav_date: '2026-06-07', status: 'SUBMITTED', slip_image_path: null,
    broker_code_arn: 'ARN-12345', sub_broker_arn: 'BR001', euin: 'E-123456',
    euin_declaration: false, ref_no: 'BR001-260002',
  },
  {
    id: 'm003', slip_no: 'BR001-260003',
    salutation: 'Mr.', unitholder_name: 'Arun Venkataraman', pan: 'KLMNO9012P', folio_no: 'F345678',
    scheme_id: 's004', scheme_name: 'UNION Tax Saver Fund (ELSS)', plan: 'Regular', option: 'Growth',
    facility: 'Lumpsum', frequency: 'One Time',
    transaction_types: ['SWITCH'],
    switch_from_scheme: 'UNION Large Cap Fund', switch_from_plan: 'Regular', switch_from_option: 'Growth',
    switch_to_scheme: 'UNION Tax Saver Fund (ELSS)', switch_to_plan: 'Regular', switch_to_option: 'Growth',
    switch_amount: 100000, switch_amount_words: 'One Lakh Only',
    switch_all_units: false, switch_units: null,
    submitted_at: '2026-06-07T14:10:00Z', applicable_nav_date: '2026-06-09', status: 'SUBMITTED', slip_image_path: null,
    broker_code_arn: 'ARN-12345', sub_broker_arn: 'BR001', euin: 'E-123456',
    euin_declaration: false, ref_no: 'BR001-260003',
  },
  {
    id: 'm004', slip_no: 'BR001-260004',
    salutation: 'Ms.', unitholder_name: 'Sunita Mehta', pan: 'PQRST3456U', folio_no: 'F456789',
    scheme_id: 's003', scheme_name: 'UNION Balanced Advantage Fund', plan: 'Regular', option: 'Growth',
    facility: 'Lumpsum', frequency: 'One Time',
    transaction_types: ['REDEMPTION'],
    redemption_amount: 75000, redemption_amount_words: 'Seventy Five Thousand Only',
    redemption_all_units: false, redemption_units: null,
    redemption_credit_to: 'Default Bank Account',
    submitted_at: '2026-06-08T09:05:00Z', applicable_nav_date: '2026-06-09', status: 'SUBMITTED', slip_image_path: null,
    broker_code_arn: 'ARN-12345', sub_broker_arn: 'BR001', euin: 'E-123456',
    euin_declaration: false, ref_no: 'BR001-260004',
  },
  {
    id: 'm005', slip_no: 'BR001-260005',
    salutation: 'Mr.', unitholder_name: 'Mohammed Farooq', pan: 'UVWXY7890Z', folio_no: 'F567890',
    scheme_id: 's005', scheme_name: 'UNION Liquid Fund', plan: 'Regular', option: 'Growth',
    facility: 'Lumpsum', frequency: 'One Time',
    transaction_types: ['PURCHASE'],
    purchase_payment_mode: 'RTGS', purchase_amount: 200000,
    purchase_amount_words: 'Two Lakh Only',
    purchase_cheque_utr_no: 'UTR456789012', purchase_transaction_date: '2026-06-08',
    purchase_source_bank_ac: '11223344556', purchase_source_bank_name: 'SBI',
    purchase_source_branch: 'Fort', purchase_account_type: 'Current',
    purchase_third_party_declaration: false,
    submitted_at: '2026-06-08T11:30:00Z', applicable_nav_date: '2026-06-09', status: 'RECONCILED', slip_image_path: null,
    broker_code_arn: 'ARN-12345', sub_broker_arn: 'BR001', euin: 'E-123456',
    euin_declaration: true, ref_no: 'BR001-260005',
  },
  {
    id: 'm006', slip_no: 'BR001-260006',
    salutation: 'Ms.', unitholder_name: 'Deepa Krishnaswamy', pan: 'LMNOP6789Q', folio_no: 'F678901',
    scheme_id: 's003', scheme_name: 'UNION Balanced Advantage Fund', plan: 'Direct', option: 'Growth',
    facility: 'Lumpsum', frequency: 'One Time',
    transaction_types: ['PURCHASE'],
    purchase_payment_mode: 'Cheque', purchase_amount: 150000,
    purchase_amount_words: 'One Lakh Fifty Thousand Only',
    purchase_cheque_utr_no: 'CHQ654321', purchase_transaction_date: '2026-06-08',
    purchase_source_bank_ac: '66778899001', purchase_source_bank_name: 'Axis Bank',
    purchase_source_branch: 'Powai', purchase_account_type: 'Savings',
    purchase_third_party_declaration: false,
    submitted_at: '2026-06-08T13:55:00Z', applicable_nav_date: '2026-06-09', status: 'SUBMITTED', slip_image_path: null,
    broker_code_arn: 'ARN-12345', sub_broker_arn: 'BR001', euin: 'E-123456',
    euin_declaration: false, ref_no: 'BR001-260006',
  },
]
